# Generated by Django 3.2 on 2021-06-24 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True, validators=[myapp.models.mobile])),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/customerProfilePic/')),
                ('id_proof', models.FileField(default=True, upload_to='id_proofs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True, validators=[myapp.models.mobile])),
                ('id_proof', models.FileField(upload_to='id_proofs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True, validators=[myapp.models.mobile])),
                ('id_proof', models.FileField(upload_to='id_proofs', verbose_name='Registration document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('mobile', models.CharField(max_length=50, validators=[myapp.models.mobile])),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bio_data', models.FileField(upload_to='bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('vaccine', models.CharField(choices=[('Polio', 'Polio'), ('Typhoid', 'Typhoid'), ('Chicken pox', 'Chicken pox'), ('Hepatitis', 'Hepatitis')], default='Polio', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionsToLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.FileField(blank=True, null=True, upload_to='lab_reports')),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctorprofile')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to='lab_reports')),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctorprofile')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('Blood pressure', 'Blood pressure'), ('Blood sugar', 'Blood sugar'), ('Cholesterol', 'Cholesterol')], max_length=50)),
                ('symptoms', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/HIProfilePic/')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True, validators=[myapp.models.mobile])),
                ('id_proof', models.FileField(upload_to='id_proofs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerprofile')),
            ],
        ),
    ]
