# Generated by Django 3.2.5 on 2021-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_labreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='report',
            field=models.FileField(upload_to='lab_reports'),
        ),
    ]
