# Generated by Django 3.2.7 on 2021-09-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbooking',
            name='symptoms',
        ),
    ]
