# Generated by Django 3.2.7 on 2021-09-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_daily_booking_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_booking_limit',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
