# Generated by Django 3.2.7 on 2021-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_daily_booking_limit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccancyLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancyapply',
            name='dob',
            field=models.DateField(help_text='DD/MM/YYYY', verbose_name='Date of birth'),
        ),
    ]
