# Generated by Django 3.2.7 on 2021-10-04 05:36

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hi',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[myapp.models.mobile]),
        ),
        migrations.AlterField(
            model_name='lab',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[myapp.models.mobile]),
        ),
        migrations.AlterField(
            model_name='vacancyapply',
            name='mobile',
            field=models.CharField(max_length=10, validators=[myapp.models.mobile]),
        ),
    ]
