# Generated by Django 3.2.7 on 2021-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211006_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='lab',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='prescriptionstolab',
            name='prescription',
            field=models.TextField(default=' '),
        ),
    ]
