# Generated by Django 3.2.7 on 2021-10-07 05:02

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20211006_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 5, 2, 32, 468734, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
    ]
