# Generated by Django 3.2.7 on 2021-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20211006_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id_type',
            field=models.CharField(choices=[('idtype', 'id_type')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='id_type',
            field=models.CharField(choices=[('idtype', 'id_type')], default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hi',
            name='id_type',
            field=models.CharField(choices=[('idtype', 'id_type')], default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='id_type',
            field=models.CharField(choices=[('idtype', 'id_type')], default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hi',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='vacancyapply',
            name='address',
            field=models.TextField(default=' '),
        ),
    ]
