# Generated by Django 3.2.7 on 2021-10-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20211016_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapply',
            name='preference',
            field=models.CharField(choices=[('samplejob', 'sample_job'), ('samplejob', 'sample_job'), ('samplejob', 'sample_job'), ('samplejob', 'sample_job')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
