# Generated by Django 3.2.7 on 2021-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_vacancyapply_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbooking',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
