# Generated by Django 3.2.8 on 2021-10-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
