# Generated by Django 3.2.8 on 2021-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_jobs_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
