# Generated by Django 3.2.8 on 2021-10-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_jobs_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapply',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs'),
        ),
    ]
