# Generated by Django 3.2.7 on 2021-11-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_vacancyapply_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id_type',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('PAN Card', 'PAN Card'), ('Driving licence', 'Driving licence')], max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='id_type',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('PAN Card', 'PAN Card'), ('Driving licence', 'Driving licence')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hi',
            name='id_type',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('PAN Card', 'PAN Card'), ('Driving licence', 'Driving licence')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lab',
            name='id_type',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('PAN Card', 'PAN Card'), ('Driving licence', 'Driving licence')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='vacancyapply',
            name='preference',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs'),
        ),
    ]
