# Generated by Django 3.2.7 on 2021-11-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20211108_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Specify if any ', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctorprofile'),
        ),
    ]
