# Generated by Django 3.2.7 on 2021-11-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_labreport_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbooking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
