# Generated by Django 3.2.7 on 2021-11-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_labbooking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='id_type',
        ),
    ]
